### ISSUE TITLE
headless firefox

### ISSUE THREAD

**Issue by steve-ayerhart** [her01n/guile-web-driver#1]
This isn't really an issue. I was just browsing your code and saw [this comment.](https://github.com/her01n/guile-web-driver/blob/master/web/driver.scm#L106)

Just wanted to let you know you can get the geckodriver to open firefox in headless mode by passing the correct [capabilities](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions).

Using something like
`{
  "capabilities": {
    "alwaysMatch": {
      "browserName": "firefox",
      "moz:firefoxOptions": {
        "args": ["-headless"],
      }
    },
    "firstMatch": [
      {"platformName": "linux"}
    ]
  }
}`

**Comment by her01n** [comment]
Thank you for your note.

I am going to remove the hack and use this option.
