### ISSUE TITLE
LICENSE: Is it "GPLv3 only" or "GPLv3 or later"?

### ISSUE THREAD

**Issue by artyom-poptsov** [her01n/guile-web-driver#3]
Could you please specify the project license more precise?  

I made a [fork](https://github.com/artyom-poptsov/guile-web-driver-ng) of your project to speed up the development process and add features that I need.  Currently I specified the license as "GPLv3 only" as you didn't mention the license elsewhere aside from the `LICENSE` file, but from my experience most of the projects that use GPL allow to use newer versions of the license (e.g. "GPLv3 or later".)  From my humble opinion it makes sense as GPL tends to be updated to address discovered issues in it.  Is it also the case with `guile-web-driver`?  Can I use "GPLv3 or later"?

Thanks for your work on `guile-web-driver`, by the way!

-avp

**Comment by her01n** [comment]
Uupdated the readme to clarify. License is "GPLv3 or later".

**Comment by artyom-poptsov** [comment]
Thanks!  Much appreciated.

-avp
